// <auto-generated />
using Funcionario_ApiWeb.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Funcionario_ApiWeb.NET.Migrations
{
    [DbContext(typeof(FuncionarioDbContext))]
    [Migration("20211028211013_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Funcionario_ApiWeb.NET.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("char(14)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("char(14)");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionario");

                    b.HasData(
                        new
                        {
                            IdFuncionario = 1,
                            CPF = "063.485.221-32",
                            Cargo = "Analista de Logistisca JR",
                            Email = "ronaldopeira658@gmail.com",
                            Idade = 24,
                            NomeCompleto = "Ronaldo Pereira Cruz",
                            Salario = 3100.00m,
                            Telefone = "(65)98132-4241"
                        },
                        new
                        {
                            IdFuncionario = 2,
                            CPF = "026.752.421-25",
                            Cargo = "Analista Financeiro Pleno ",
                            Email = "carollineSouza123@gmail.com",
                            Idade = 26,
                            NomeCompleto = "Carolline Hererro Souza",
                            Salario = 4200.00m,
                            Telefone = "(65)98421-6532"
                        },
                        new
                        {
                            IdFuncionario = 3,
                            CPF = "542.481.263-78",
                            Cargo = "Analista de RH Senior",
                            Email = "Leandrocardosom5874@gmail.com",
                            Idade = 33,
                            NomeCompleto = "Leandro Cardoso Monteiro",
                            Salario = 5600.00m,
                            Telefone = "(65)98365-6421"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
